POST https://convitex-back.onrender.com/guest
Content-Type: application/json

{
  "nome":"Zé das Couve",
  "tipo": "Ola",
  "status": "Pendente"
}


###

GET https://convitex-back.onrender.com/guest

###

DELETE https://convitex-back.onrender.com/delete/05b55e0b-2c80-4e66-81fe-b547dcdc518e
